#!/bin/bash

if [ $# -eq 0 ];  then
  echo "Usage:"
  echo "$0 install"
  echo "$0 uninstall"
  echo ""
  echo "Examples:"
  echo "$0 install --prefix=/usr/local"
  echo "$0 install --flatpak --prefix=/app"
exit
fi

# parse command line arguments
for i in "$@"
do
case $i in
    -p=*|--prefix=*)
    INSTALL_PREFIX="${i#*=}"
    ;;
    --flatpak)
    FLATPAK="true"
    ;;
    *)
            # unknown option
    ;;
esac
done

# Defaults for non flatpak install
APPLICATIONSDIR=~/.local/share/applications
UIC="gtk-update-icon-cache"
UDD="update-desktop-database ${APPLICATIONSDIR}"
WINE_CMD=$(which wine)
WINETRICKS_CMD=$(which winetricks)
TMPDIR=/tmp
WINEZPREFIX="~/.local/share/winezgui"

if [ -z "${INSTALL_PREFIX}" ]; then
   INSTALL_PREFIX="/usr"
fi

if [ "${FLATPAK}" = "true" ]; then
     echo setting prefix and paths for flatpak
     INSTALL_PREFIX="/app"
  # Set flatpak command for flatpak-spawn
#  sed -e "s|\(WINEEXE=\).*| \1\"flatapk-spawn run --command=wine\"|g" -i ${INSTALL_PREFIX}/bin/winezgui
  UIC="flatpak-spawn --host gtk-update-icon-cache"
  UDD="flatpak-spawn --host update-desktop-database ${APPLICATIONSDIR}"
  WINE_CMD="flatpak run --command=wine org.winehq.Wine"
  WINETRICKS_CMD="flatpak run --command=winetricks org.winehq.Wine"
  TMPDIR="~/.var/app/io.github.WineZGUI/data/tmp"
  WINEZPREFIX="~/.var/app/io.github.WineZGUI/data/prefixes"
fi     
##

if [ "$1" = "install" ]; then
  mkdir -p ${INSTALL_PREFIX}/share/icons/hicolor/scalable/apps/
  mkdir -p ${INSTALL_PREFIX}/share/applications/
  mkdir -p ${INSTALL_PREFIX}/bin/
  
  install -Dvm644 ./assets/winezgui.svg        ${INSTALL_PREFIX}/share/icons/hicolor/scalable/apps/
  install -Dvm644 ./assets/winezgui.desktop    ${INSTALL_PREFIX}/share/applications/
  install -Dvm755 ./bin/winezgui               ${INSTALL_PREFIX}/bin/
  install -Dvm755 ./bin/winezgui-create-prefix ${INSTALL_PREFIX}/bin/
  echo $INSTALL_PREFIX IS INSTALL_PREFIX
  echo ${INSTALL_PREFIX}/bin/winezgui-create-prefix
  sed "s|BINDIR=/usr|BINDIR=$INSTALL_PREFIX|g" -i ${INSTALL_PREFIX}/bin/winezgui
  sed "s|RUN_UPDATE_ICON_CACHE=.*|RUN_UPDATE_ICON_CACHE=\"$UIC\"|g" -i ${INSTALL_PREFIX}/bin/winezgui-create-prefix
  sed "s|RUN_UPDATE_DESKTOP_DATABASE=.*|RUN_UPDATE_DESKTOP_DATABASE=\"$UDD\"|g" -i ${INSTALL_PREFIX}/bin/winezgui-create-prefix
  sed "s|WINETRICKS_CMD=.*|WINETRICKS_CMD=\"$WINETRICKS_CMD\"|g" -i ${INSTALL_PREFIX}/bin/winezgui-create-prefix
  sed "s|WINE_CMD=.*|WINE_CMD=\"$WINE_CMD\"|g" -i ${INSTALL_PREFIX}/bin/winezgui-create-prefix
  sed "s|TMPDIR=.*|TMPDIR=\"$TMPDIR\"|g" -i ${INSTALL_PREFIX}/bin/winezgui-create-prefix
  sed "s|WINEZPREFIX=.*|WINEZPREFIX=\"$WINEZPREFIX\"|g" -i ${INSTALL_PREFIX}/bin/winezgui-create-prefix
  sed "s|WINEZPREFIX=.*|WINEZPREFIX=\"$WINEZPREFIX\"|g" -i ${INSTALL_PREFIX}/bin/winezgui

# debug
echo WINEZPREFIX=$WINEZPREFIX
  
echo "
rm -vf ${INSTALL_PREFIX}/share/icons/hicolor/scalable/apps/winezgui.svg
rm -vf ${INSTALL_PREFIX}/share/applications/winezgui.desktop
rm -vf ${INSTALL_PREFIX}/bin/winezgui
rm -vf ${INSTALL_PREFIX}/bin/winezgui-create-prefix
"> ./uninstall

elif [ "$1" = "uninstall" ]; then
 if [ -f ./uninstall ]; then
    sh ./uninstall
    rm ./uninstall
 else
    echo "not installed"
 fi

else
  echo "Usage:"
  echo "$0 install"
  echo "$0 uninstall"
  echo ""
  echo "Examples:"
  echo "$0 install --prefix=/usr/local"
  echo "$0 install --flatpak --prefix=/app"
fi
