#!/usr/bin/env bash

#check-all-variables
check-all-variables()
{
  ### Debug Check variables which are used in this file up to this point
  SOURCE "check-variable"
  echo "-------------------------------${FUNCNAME[0]}------------------------------------------"
  #Skip checking for flatpakid and flatpak_name in system install
  for VARIABLE in $1;
  do
     if [ "${VARIABLE}" = "FLATPAK_NAME" ] && [ "${INSTALL_TYPE}" = "system" ]; then
          continue;
     elif [ "${VARIABLE}" = "SHORT_FLATPAK_NAME" ] && [ "${INSTALL_TYPE}" = "system" ];then
           continue
     fi
           
     check-variable "${0}" "$VARIABLE"
  done

  if [ "${DEBUG}" = "Y" ]; then
       echo ""-----------------------------------------------------------------------------------""
  else
       echo ""
  fi
  ### Debug Check variables which are used in this file up to this point
}