#!/usr/bin/env bash

#check-variable
check-variable()
{
  if [ $# -lt 2 ]; then 
    echo "need 2 arguments, filename and variable to test"
    return
  fi

  if [ -z "${!2}" ]; then
    echo "Error $2 not defined in $1"
    return
  fi

  if [ "${DEBUG}" = "Y" ]; then
    echo "Defined: $2=${!2}"
  else
    echo -n "."
  fi
}
