#!/usr/bin/env bash
script-quit()
{
  dbug "I: Script: Launched ${FUNCNAME[0]}"
  
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  echo "I: Bye! :-)"
  exit 0
}
