#!/usr/bin/env bash
# script-open-file-manager
script-open-file-manager()
{
  dbug "I: Script: Launched ${FUNCNAME[0]}"
  
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  xdg-open "${EXE_PATH}"
}
