#!/usr/bin/env bash
#script-get-selected-exes-for-shortcuts
# FIXME perhaps usable for create shortcuts / delete shortcuts
script-get-selected-exes-for-shortcuts()
{
 dbug "I: Script: Launched ${FUNCNAME[0]}"
   
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
 unset COMMAND
 unset count
 unset SHOW_OPTION
 unset NAMES
 unset FILES
 unset LIST_OF_EXES_FOR_SHORTCUTS
 unset search_list


 count=0
 NAMES=()
 FILES=()
 # Find all exe files in drive_c Exclude windows directory,
 # and common exe files present in Program Files directory
 # Add those files to FILES array and filenames to NAMES array
 SOURCE "script-get-installed-exe-files"
 script-get-installed-exe-files
 EXE_LIST="${EXE_FILES_FOUND}"
 search_list=$(echo "${EXE_LIST}"|tr "\n" "|")

echo "=================================="
echo "$search_list"
 exe_found=$(echo ${search_list}|grep -i "exe")

 if [ -z "${exe_found}" ] ; then
 #     ${ZENITY_CMD} --error --title "${PROGNAME} - no exe installed!" \
 #            --text "Sorry, no exe found in prefix: \"${PREFIXNAME}\""
      return 1
 fi

 SAVEIFS=${IFS}
 IFS=$(echo -en "\n\b")

 # if exe_found has value, then only change exe
 for i in $(echo ${search_list}|tr '|' '\n'|sort)
 do
     RealName=$(basename "$i")
     RealFile=$(realpath -m "$i")

     # If 1st value is empty, enable it
     SHOW_OPTION+="TRUE \"${RealName}\""
     SHOW_OPTION+=" "
     NAMES+=("${RealName}")
     FILES+=("${RealFile}")
  
     count=$(expr ${count} + 1)
 done
 IFS=${SAVEIFS}


# Generate Height value
SOURCE "winezgui-get-window-height"
winezgui-get-window-height ${#FILES[@]}

# if [ ${#FILES[@]} -eq 1 ]; then
#      export SELECTED_EXE="${FILES}"
# --height=300s     
# else
     # 3. Show the found exe files using zenity
     unset COMMAND
     COMMAND+="${ZENITY_CMD}  --title=\"${APP_WITH_VER} - Shortcuts\" "
     COMMAND+="--list --checklist --width=460 --height=${HEIGHT} "
     COMMAND+="--text=\"${PREFIXNAME}, choose exe for shortcuts...\" "
     COMMAND+="--hide-header --column \" \" --column \"Action\" ${SHOW_OPTION}"
     LIST_OF_EXES_FOR_SHORTCUTS=$(eval ${COMMAND})

     if [ -z "${LIST_OF_EXES_FOR_SHORTCUTS}" ]; then
          echo "Cancelled!"
          Script_Window
     fi
    export LIST_OF_EXES_FOR_SHORTCUTS
    echo "${LIST_OF_EXES_FOR_SHORTCUTS}"

     count=0
    # # 4. Find which file the user selected and set the selected exe into variable
    #  for i in "${NAMES[@]}"; do
    #      if [ "$i" = "$LIST_OF_EXES_FOR_SHORTCUTS" ]; then
    #           echo "Selected $i"
    #           echo "File is ${FILES[${count}]}"
    #           export SELECTED_EXE="${FILES[${count}]}"
    #           export SELECTED_EXE_NAME=$(basename "${SELECTED_EXE}")
    #           break
    #      fi
    #      count=$(expr ${count} + 1)
    #  done
# fi
}
