#!/usr/bin/env bash
# winezgui-show-help
script-help()
{
  dbug "I: Script: Launched ${FUNCNAME[0]}"
  
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  BASE_EXE_PATH=$(basename "${EXE_PATH}")
  BASE_SCRIPT=$(basename "${SCRIPTFILE}")
  unset HELP_TEXT
  HELP_TEXT+="Launch...            : Launches \"<b>${PROGNAME}</b>\" with default exe ${EXE_NAME}|"
  HELP_TEXT+="Open Other EXE...    : Run setup or other exe with \"<b>${PREFIXNAME}</b>\" prefix!|"
  HELP_TEXT+="Winetricks GUI...    : Launches winetricks gui for the prefix. Use it to configure.|"
  HELP_TEXT+="Winetricks CLI...    : Install winetricks verbs unattended/silently|"
  HELP_TEXT+="Wine Programs...     : Run wine programs like regedit, winecfg, etc. |"
  HELP_TEXT+="Open File Manager... : Open directory \"<b>${BASE_EXE_PATH}</b>\" with file manager|"
  HELP_TEXT+="Open Shell...        : Open directory \"<b>${PREFIXNAME}</b>\" with gnome-terminal|"
  HELP_TEXT+="Change...            : Name, Prefix, Default Exe, Icon, and Category|"
  HELP_TEXT+="Backup...            : Make backups or Create Game Bundles|"
  HELP_TEXT+="Save/Load...         : Save/Load drive_c/${USER} directory inside prefix|"
  HELP_TEXT+="More...              : More options like Delete, etc.|"
  HELP_TEXT+="About...             : Details about \"<b>${PREFIXNAME}</b>\"|"
  HELP_TEXT+="Help...              : This help|"
  # Last line must not end with |"
  HELP_TEXT+="Quit...              : Exits ${BASE_SCRIPT}"

  # Text is more, so we need to format it, with sed in pango markup

  unset TEXT TEXT1
  TEXT1=$(printf "%s\n" "$HELP_TEXT" | tr "|" "\n" | while read -r line; do echo $line \
        |sed '0,/:/{s/:/ \`: /}'|sed -e 's/$/XX/g'|sed 's/^/<tt><b>/g'|sed 's/`:/<\/b>`:<small>/g'; done)

  TEXT="$(echo $TEXT1|sed -e 's/XX /<\/small><\/tt>\n/g'|sed -e 's/XX/<\/small><\/tt>\n/g'|column -t -s '\`')"

  ${ZENITY_CMD} --info --no-wrap --text "${TEXT}"
  unset HELP_TEXT
  unset TEXT BASE_SCRIPT BASE_EXE_PATH
}
