#!/usr/bin/env bash
#script-create-found-new-exe-files-file

script-create-found-new-exe-files-file()
{
  dbug "I: Script: Launched ${FUNCNAME[0]}"
  
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  FOUND_EXE_FILES="found-exe-files.yml"
  SOURCE "script-get-installed-exe-files"
  script-get-installed-exe-files
  EXE_LIST="${EXE_FILES_FOUND}"
  echo "${EXE_LIST}" |sed "s|${PREFIXDIR}|\${PREFIXDIR}|g" \
     > "${PREFIXDIR}/${FOUND_EXE_FILES}"
}
