#!/usr/bin/env bash
#script-delete-scriptfile
script-delete-scriptfile()
{
  
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  # Delete Shortcuts and Prefix Directory
  rm -f  "${DESKTOPFILE}" "${SCRIPTFILE}" && \
  dbug "I: Script: Delete: Removed ${SCRIPTFILE}" || \
  echo "E: Script: Delete: Cannot Remove ${SCRIPTFILE} !!"

  dbug "I: Script: Delete: Removed broken WineZGUI .desktop links"
  # Clean up broken shortcuts and update shortcuts menu
  SOURCE "winezgui-remove-broken-links"
  winezgui-remove-broken-links

  dbug "I: Script: Delete: Exiting!"
  ${ZENITY_CMD} --info --no-wrap --text "Deleted ${SCRIPTFILE}" --title "${APP_WITH_VER} - Delete Script!"
  # Exit after deleting prefix
  exit 0
}