#!/usr/bin/env bash
#script-save-load 
script-save-load()
{
  dbug "I: $(basename ${0}): Launched ${FUNCNAME[0]}"
  
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not

  # For Zenity 4
  ZENITY_VERSION=$(${ZENITY_CMD} --version|cut -f1 -d ".")
  if [ "${ZENITY_VERSION}" -eq 4 ]; then
       WINDOW_HEIGHT=500
       WINDOW_WIDTH=500
  else
       WINDOW_HEIGHT=340
       WINDOW_WIDTH=360
  fi

  SAVE_LOAD_OPTION=$(${ZENITY_CMD} --title "${APP_WITH_VER} - Save/Load" \
                    --list   --hide-header                   \
                    --width=${WINDOW_WIDTH}                  \
                    --height=${WINDOW_HEIGHT}                \
                    --radiolist --column " "                 \
                    --column "Action"                        \
                            0 "Save..."                      \
                            0 "Load..."                      \
                            0 "Help..."                      \
                    --text   "Save/Load..."                  )

  dbug "${0}: ${FUNCNAME[0]}: ${SAVE_LOAD_OPTION} Selected!"
  # Exit if Cancel is clicked
  if   [ -z "${SAVE_LOAD_OPTION}" ]; then
         dbug "I: $(basename ${0}): ${FUNCNAME[0]}: Cancel Selected!"
         return 1
  fi
  
  if   [ "${SAVE_LOAD_OPTION}" = "Set Saved Game directory..."  ]; then
         SOURCE "script-save-load-set-saved-game-directory"
         script-save-load-set-saved-game-directory
  elif [ "${SAVE_LOAD_OPTION}" = "Save..."  ]; then
         SOURCE "script-save-load-save"
         script-save-load-save
  elif [ "${SAVE_LOAD_OPTION}" = "Load..."  ]; then
         SOURCE "script-save-load-load"
         script-save-load-load
  elif [ "${SAVE_LOAD_OPTION}" = "Help..."  ]; then
         SOURCE "script-save-load-help"
         script-save-load-help
  fi
}
