#!/usr/bin/env bash
# script-more
# FIXME add create/rename/delete shortcuts
script-more()
{
  dbug "I: Script: Launched ${FUNCNAME[0]}"
  
  # For Zenity 4
  ZENITY_VERSION=$(${ZENITY_CMD} --version|cut -f1 -d ".")
  if [ "${ZENITY_VERSION}" -eq 4 ]; then
       WINDOW_HEIGHT=500
       WINDOW_WIDTH=500
  else
       WINDOW_HEIGHT=240
       WINDOW_WIDTH=360
  fi
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  SCRIPT_MORE_OPTION=$(${ZENITY_CMD} --title "${PROGNAME} - More"     \
                              --list   --hide-header                  \
                              --width=${WINDOW_WIDTH}                 \
                              --height=${WINDOW_HEIGHT}               \
                              --radiolist --column " "                \
                              --column "Action"                       \
                                     0 "Set Environment Variable"     \
                                     0 "Set Exe Arguments"            \
                                     0 "Set Launch Behavior"          \
                                     0 "Import Game Directory"        \
                                     0 "Import Runner into prefix..." \
                                     0 "Delete..."                    \
                                --text "More..."                      )

  # Exit if Cancel is clicked
  if [ -z "${SCRIPT_MORE_OPTION}" ]; then
       dbug "I: MORE: Cancel Selected!"
       return 1
  fi

  if [ "${SCRIPT_MORE_OPTION}" = "Set Environment Variable" ]; then
       dbug "I: Script: Delete... Selected!"
       SOURCE "script-set-environment-variable"
       script-set-environment-variable
  fi

  if [ "${SCRIPT_MORE_OPTION}" = "Set Exe Arguments" ]; then
       dbug "I: Script: Set Exe Arguments... Selected!"
       SOURCE "script-exe-cmdline"
       script-exe-cmdline
  fi  
  
  if [ "${SCRIPT_MORE_OPTION}" = "Set Launch Behavior" ]; then
       dbug "I: Script: Set Launch Behavior... Selected!"
       SOURCE "script-more-launch-behavior"
       script-more-launch-behavior
  fi  
  
  if [ "${SCRIPT_MORE_OPTION}" = "Import Game Directory" ]; then
       dbug "I: Script: Import Game Directory... Selected!"
       SOURCE "script-import-gamedir-into-prefix"
       script-import-gamedir-into-prefix
  fi

  if [ "${SCRIPT_MORE_OPTION}" = "Import Runner into prefix..." ]; then
       dbug "I: Script: Import Runner into prefix... Selected!"
       SOURCE "script-import-runner-into-prefix"
       script-import-runner-into-prefix
  fi

  if [ "${SCRIPT_MORE_OPTION}" = "Delete..." ]; then
       dbug "I: Script: Delete... Selected!"
       SOURCE "script-delete"
       script-delete
  fi
}
