#!/usr/bin/env bash
script-delete()
{
  dbug "I: Script: Launched ${FUNCNAME[0]}"
  
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  unset DEL_RESPONSE
  # For Zenity 4
  ZENITY_VERSION=$(${ZENITY_CMD} --version|cut -f1 -d ".")
  if [ "${ZENITY_VERSION}" -eq 4 ]; then
       WINDOW_HEIGHT=360
       WINDOW_WIDTH=400
  else
       WINDOW_HEIGHT=200
       WINDOW_WIDTH=360
  fi

  DEL_RESPONSE=$(${ZENITY_CMD}                        \
               --title "${PROGNAME}"                  \
               --list   --hide-header                 \
               --width=${WINDOW_WIDTH}                \
               --height=${WINDOW_HEIGHT}              \
               --radiolist --column " "               \
               --column "Action"                      \
                   TRUE "Delete Shortcut..."          \
                      0 "Delete Script..."            \
                      0 "Delete Prefix..."            \
                      0 "Help..."                     \
               --text   "<b>${EXE_NAME} Prefix...</b>")
  # If Cancel is clicked
  if [ -z "${DEL_RESPONSE}" ]; then
       dbug "I: Script: Delete: Cancelled!"
       unset DEL_RESPONSE
       return 1
  fi
  
  if   [ "${DEL_RESPONSE}" = "Delete Shortcut..." ]; then
         SOURCE "script-delete-shortcut"
         script-delete-shortcut

  elif [ "${DEL_RESPONSE}" = "Delete Script..." ]; then
         SOURCE "script-delete-scriptfile"
         script-delete-scriptfile
         
  elif [ "${DEL_RESPONSE}" = "Delete Prefix..." ]; then
         SOURCE "script-delete-prefix"
         script-delete-prefix
         
  elif [ "${DEL_RESPONSE}" = "Help..." ]; then
         SOURCE "script-delete-help"
         script-delete-help # Call the function in the above file

  fi

}
