#!/usr/bin/env bash
# winezgui-settings-launch-behavior
winezgui-settings-launch-behavior()
{
  HEADER="$(basename ${0}): ${FUNCNAME[0]}"
    
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  dbug "I: $(basename ${0}): Launched ${FUNCNAME[0]}"
  SOURCE "winezgui-list-available-prefixes"
  winezgui-list-available-prefixes

  # For Zenity 4
  ZENITY_VERSION=$(${ZENITY_CMD} --version|cut -f1 -d ".")
  if [ "${ZENITY_VERSION}" -eq 4 ]; then
       WINDOW_HEIGHT=300
       WINDOW_WIDTH=500
  else
       WINDOW_HEIGHT=240
       WINDOW_WIDTH=360
  fi

  GET_LAUNCH_BEHAVIOR=$(${ZENITY_CMD} --title "${APP_WITH_VER}"   \
                               --list   --hide-header      \
                               --width=${WINDOW_WIDTH}     \
                               --height=${WINDOW_HEIGHT}   \
                               --radiolist --column " "    \
                               --column "Action"           \
                                      0 "Directly..."      \
                                      0 "Script Window..." \
                                --text   "Launch..."       )
  
  if [ -z "${GET_LAUNCH_BEHAVIOR}" ]; then
       echo "Cancelled!"
       return 1
  fi
  
  dbug "I: ${HEADER}: Selected ${GET_LAUNCH_BEHAVIOR}!"
  
  if [ "${GET_LAUNCH_BEHAVIOR}" = "Directly..." ]; then
       if [ -w "${SELECTED_PREFIX}" ]; then
            echo "Yes" > "${SELECTED_PREFIX}/launch"
            dbug "I: ${HEADER}: launch file created!"
       fi
       dbug "I: ${HEADER}: ${SELECTED_PREFIX} is set to launch directly"
  else
       if [ -f "${SELECTED_PREFIX}/launch" ]; then
            dbug "I: ${HEADER}: Removing Direct launch file"
            rm "${SELECTED_PREFIX}/launch"
       else
            dbug "I: ${HEADER}: launch file not found..."
            dbug "I: ${HEADER}: Already set to open script window"
       fi
  fi
  return 0
}
