#!/usr/bin/env bash
# winezgui-settings-help
winezgui-settings-help()
{
  HEADER="$(basename ${0}): ${FUNCNAME[0]}"
    
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  dbug "I: $(basename ${0}): Launched ${FUNCNAME[0]}"
  unset HELP_TEXT
  HELP_TEXT+="Wine Arch...      : Set wine arch for new prefixes|"
  HELP_TEXT+="Prefix Template...: Set default prefix template for new scripts|"
  HELP_TEXT+="Launch Behavior...: Launch exe directly or show exe script window|"
  HELP_TEXT+="Debug Messages... : Set On / Off Debug message in terminal!|"
  HELP_TEXT+="Edit WZT-Info pre Bundle... : Allow editing of WZT-Info.yml before creating Bundle..."
  HELP_TEXT+="Disable Shortcuts... : Enable / Disable Shortcut Creation!|"

  # Text is more, so we need to format it, with sed in pango markup
  unset TEXT
  TEXT="$(echo ${HELP_TEXT}                         \
          |tr "|" "\n"                              \
          |sed "s/https:/https|/g"                  \
          |sed -E "s/([0-9]):([0-9])/\1|\2/g"       \
          |sed "s/:/;:;/g"                          \
          |column -t -s ";"                         \
          |sed -E "s/^(.*:)/<tt><b>\1<\/b><\/tt>/"  \
          |sed -E "s/^(.*)$/<small>\1<\/small>/"    \
          |sed "s/|/:/g" )"
  ${ZENITY_CMD} --info --text "${TEXT}" --title "${APP_WITH_VER} - Settings!"
  unset HELP_TEXT
  unset TEXT
  # Go back to Settings after showing help!
  return 0
}