#!/usr/bin/env bash
# winezgui-create-about-yml
# Create Metadata About.yml for the default wine prefix
# Update info only when wine is found
winezgui-create-about-yml()
{
  HEADER="$(basename ${0}): ${FUNCNAME[0]}"
  dbug "I: ${HEADER}: started"
     
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not

  dbug "I: $(basename ${0}): Launched ${FUNCNAME[0]}"
  if [ ! -f "${ABOUTFILE}" ] && [ $(which wine) ]; then
       echo "Application:${APPNAME}"        >  "${ABOUTFILE}"
       echo "Version:${APPVERSION}"         >> "${ABOUTFILE}"
       echo "Copyright:${COPYRIGHT}"        >> "${ABOUTFILE}"
       echo "Website:${WEBSITE}"            >> "${ABOUTFILE}"
       echo "Author:${AUTHOR}"              >> "${ABOUTFILE}"
       echo "E-mail:${EMAIL}"               >> "${ABOUTFILE}"
       echo "Wine Runner:${RUNNER}"         >> "${ABOUTFILE}"
       echo "Wine Version:${WINEVER}"       >> "${ABOUTFILE}"
       echo "Template:${TEMPLATE_NAME}"     >> "${ABOUTFILE}"
       echo "Wine Arch:${WINEARCH}"         >> "${ABOUTFILE}"
       echo "WineZGUI Prefix:${WINEZGUIDIR}">> "${ABOUTFILE}"
       echo "Wine Prefix:${DEFAULT}"        >> "${ABOUTFILE}"
       echo "Creation Date:$(date)"         >> "${ABOUTFILE}"
       echo "Install Type:${INSTALL_TYPE}"  >> "${ABOUTFILE}"
       if ! [ -z "${FLATPAK_NAME}" ]; then  # If flatpak (variable has value)
       echo "Flatpak Name:${FLATPAK_NAME}"  >> "${ABOUTFILE}"
       fi
       dbug "I: ${HEADER}: Created ${ABOUTFILE}"
  fi

  dbug "I: ${HEADER}: finished"
  return 0
}
