#!/usr/bin/env bash
# winezgui-settings-debug-messages
winezgui-settings-debug-messages()
{
  HEADER="$(basename ${0}): ${FUNCNAME[0]}"
    
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  dbug "I: $(basename ${0}): Launched ${FUNCNAME[0]}"

  # For Zenity 4
  ZENITY_VERSION=$(${ZENITY_CMD} --version|cut -f1 -d ".")
  if [ "${ZENITY_VERSION}" -eq 4 ]; then
       WINDOW_HEIGHT=300
       WINDOW_WIDTH=500
  else
       WINDOW_HEIGHT=240
       WINDOW_WIDTH=360
  fi

  DEBUG_OPTION=$(${ZENITY_CMD} --title "${APP_WITH_VER}"   \
                        --list   --hide-header      \
                        --width=${WINDOW_WIDTH}     \
                        --height=${WINDOW_HEIGHT}   \
                        --radiolist --column " "    \
                        --column "Action"           \
                            TRUE "No"               \
                               0 "Yes"              \
                        --text   "Debug Messages...")

  if [ -z "${DEBUG_OPTION}" ]; then
          dbug "I: ${HEADER}: Cancelled!"
          return 1
  fi
  
  # If user selects No, delete debug from Settings.yml
  if [ "${DEBUG_OPTION}" = "No" ]; then
          dbug "I: ${HEADER}: Disabled."
          unset DEBUG
          sed "/debug:/d" -i "${SETTINGS_FILE}"
  else
          # Add debug:Y to Settings.yml and export DEBUG
          if [ -w "${SETTINGS_FILE}" ]; then
              echo "debug:Y" >> "${SETTINGS_FILE}" # add to Settings
          else
              echo "Cannot write to ${SETTINGS_FILE}"
          fi
          DEBUG="Y"
          dbug "I: ${HEADER}: Enabled."
  fi
  export DEBUG # Apply runtime
  return 0
}