#!/usr/bin/env bash
# winezgui-winecfg
winezgui-winecfg()
{
  
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not
  HEADER="$(basename ${0}): ${FUNCNAME[0]}"
  dbug "I: $(basename ${0}): Launched ${FUNCNAME[0]}"
  ${WINE_CMD} winecfg
}