#!/usr/bin/env bash
#winezgui-get-window-height
winezgui-get-window-height()
{ 
  dbug "I: $(basename ${0}): Launched ${FUNCNAME[0]}"
  HEADER="$(basename ${0}): ${FUNCNAME[0]}"
    
  SOURCE "script-check-variables-loaded-or-not"
  script-check-variables-loaded-or-not


  if [ -z "${1}" ]; then
      dbug "I: ${HEADER}: Provide a integer value"
  fi
  
  # For Zenity 4
  ZENITY_VERSION=$(${ZENITY_CMD} --version|cut -f1 -d ".")
  if [ "${ZENITY_VERSION}" -eq 4 ]; then
       HEIGHT=300
  else
       HEIGHT=155
  fi

  if [ ${1} -gt 2 ]; then
       HEIGHT=$(expr ${1} \* 24 + ${HEIGHT})
  fi    # We want max 500 px window height

  if [ ${HEIGHT} -gt 700 ]; then
       HEIGHT=700
  fi
  dbug "I: ${HEADER}: HEIGHT=${HEIGHT}"
  export HEIGHT
}
